# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py
fence = "===================================== ANSWER ===================================="

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.full_version)
np.show_config()

2.1.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/73/klh957sj02nd7k78vl8ckkcm0000gn/T/cibw-run-5i0nreza/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /private/var/folders/73/klh957sj02nd7k78vl8ckkcm0000gn/T/cibw-run-5i0nreza/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Sandybridge MAX_THREADS=64
    pc file directory: /Users/runner/work/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/73/klh957sj02nd7k78vl8ckkcm0000gn/T/cibw-run-5i0nreza/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /private/var/folders/73/klh957sj02nd7k78vl8ckkcm0000gn/T/cibw-run-5i0nreza/c

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
print(np.zeros(10))
print(fence)
answer(3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
===================================== ANSWER ====================================
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(np.size(np.zeros(10)))
print(fence)
answer(4)

10
===================================== ANSWER ====================================
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)
print(fence)
answer(5)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)
print(fence)
answer(6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
===================================== ANSWER ====================================
Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.arange(10, 50)
print(x)
print(fence)
answer(7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
===================================== ANSWER ====================================
Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x = np.arange(5)
print(x[::-1])
print(fence)
answer(8)

[4 3 2 1 0]
===================================== ANSWER ====================================
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
print(np.arange(9).reshape((3, 3)))
print(fence)
answer(9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
===================================== ANSWER ====================================
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
x = np.array([1, 2, 0, 0, 4, 0])
print(x.nonzero())
print(fence)
answer(10)

(array([0, 1, 4]),)
===================================== ANSWER ====================================
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
print(np.identity(3))
print(np.eye(3))
print(fence)
answer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
===================================== ANSWER ====================================
Z = np.eye(3)
print(Z)


**Note@[2024-10-24T16:29:04+08:00]**

In factor, there is no substantial difference between `np.identity` and `np.eye`. Inside implementation of `np.identity`, it simply invokes `np.eye` call.

```python
@set_array_function_like_doc
@set_module('numpy')
def identity(n, dtype=None, *, like=None):
    ...
    if like is not None:
        return _identity_with_like(like, n, dtype=dtype)

    from numpy import eye
    return eye(n, dtype=dtype, like=like)
```

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
print(np.random.random((3, 3, 3)))
print(fence)
answer(12)

[[[0.13491718 0.16771032 0.15516599]
  [0.28405512 0.42868143 0.06930375]
  [0.44617834 0.70112745 0.28188876]]

 [[0.74554263 0.57216385 0.94913606]
  [0.84264523 0.87243656 0.21432464]
  [0.9799172  0.20865064 0.68295638]]

 [[0.40803234 0.88200837 0.95079315]
  [0.93632094 0.79163225 0.3814622 ]
  [0.2904584  0.12332588 0.26605184]]]
===================================== ANSWER ====================================
Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
x = np.random.random((10, 10))
print(x)
print(np.max(x))
print(np.min(x))
print(x.max())
print(x.min())
print(fence)
answer(13)

[[0.40118151 0.61450049 0.9093358  0.55766102 0.42700202 0.47252793
  0.48438996 0.2538436  0.16316914 0.43268632]
 [0.10946504 0.81652952 0.08069306 0.46708497 0.68601742 0.61696451
  0.81061818 0.41984795 0.25682037 0.64752185]
 [0.14995862 0.64087436 0.94631431 0.02189195 0.99107919 0.1382678
  0.72622229 0.4090593  0.07325926 0.59255353]
 [0.16368226 0.45428224 0.96437993 0.45477888 0.95336445 0.20307932
  0.11461316 0.89690895 0.63106914 0.95343235]
 [0.39693835 0.46921454 0.87203872 0.68708902 0.62766333 0.16894364
  0.49951894 0.89707933 0.62040339 0.00518702]
 [0.70466391 0.81599698 0.33807261 0.47577899 0.86005011 0.16202047
  0.21606591 0.74414015 0.41658512 0.55161108]
 [0.58733961 0.31791937 0.24763502 0.06667986 0.39853304 0.63406476
  0.48255221 0.89864523 0.3854919  0.12868259]
 [0.9389999  0.87424117 0.4940026  0.60243044 0.53624362 0.38186992
  0.34073838 0.55158251 0.2854901  0.93934351]
 [0.3193332  0.84430039 0.34231571 0.63091876 0.60752186 0.93273714
  0.52819315 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
x = np.random.random(30)
print(np.mean(x))
print(x.mean())
print(fence)
answer(14)

0.5502983778770569
0.5502983778770569
===================================== ANSWER ====================================
Z = np.random.random(30)
m = Z.mean()
print(m)


**note@[2024-10-24T16:42:17+08:00]**

`np.mean` essentially invokes `x.mean` call

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
x = np.ones((4, 4))
x[1:-1, 1:-1] = 0
print(x)
print(fence)
answer(15)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
===================================== ANSWER ====================================
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
existed = np.random.random((3, 3))
x = np.zeros(tuple(map(lambda s:s+2, existed.shape)))
x[1:-1, 1:-1] = existed
print(x)

x = np.pad(existed, pad_width=1, mode='constant', constant_values=0)
print(x)
print(fence)
answer(16)

[[0.         0.         0.         0.         0.        ]
 [0.         0.58711642 0.1388426  0.10770973 0.        ]
 [0.         0.18479056 0.1098781  0.78099995 0.        ]
 [0.         0.14376224 0.01671065 0.67315392 0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.         0.         0.         0.         0.        ]
 [0.         0.58711642 0.1388426  0.10770973 0.        ]
 [0.         0.18479056 0.1098781  0.78099995 0.        ]
 [0.         0.14376224 0.01671065 0.67315392 0.        ]
 [0.         0.         0.         0.         0.        ]]
===================================== ANSWER ====================================
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) # precision

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
print(np.diag(1+np.arange(4), k=-1))
print(fence)
answer(18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
===================================== ANSWER ====================================
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)
print(fence)
answer(19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
===================================== ANSWER ====================================
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))
print(fence)
answer(20)

(np.int64(1), np.int64(5), np.int64(3))
===================================== ANSWER ====================================
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
block = np.array([[0, 1], [1, 0]])
print(np.tile(block, (4, 4)))
print(fence)
answer(21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
===================================== ANSWER ====================================
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
x = np.random.random((5, 5))
normalized = (x - np.mean(x)) / np.std(x)
print(normalized)
print(fence)
answer(22)

[[-1.2208573   0.0471232   1.05027179 -0.53735339  0.67401664]
 [-0.97436566 -1.25527746  0.06124432  0.83098197 -1.35298626]
 [ 0.30842165 -0.45818841 -1.51865988 -0.89534     0.29760992]
 [ 1.72845993 -0.84477382 -0.88586696  1.40912255  1.50845172]
 [ 0.2620471   0.82747733 -1.15858784  1.23304561  0.86398325]]
===================================== ANSWER ====================================
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
print(np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)]))
print(fence)
answer(23)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
===================================== ANSWER ====================================
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
A, B = np.ones((5, 3)), np.ones((3, 2))
print(np.dot(A, B))
print(A @ B)
print(fence)
answer(24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
===================================== ANSWER ====================================
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
x = np.random.randint(1, 10, size=20)
print(x)
x[(x > 3) & (x < 8)] *= -1
print(x)
print(fence)
answer(25)

[7 1 9 9 5 6 8 5 1 7 4 3 3 1 7 4 6 7 9 5]
[-7  1  9  9 -5 -6  8 -5  1 -7 -4  3  3  1 -7 -4 -6 -7  9 -5]
===================================== ANSWER ====================================
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))
print(np.sum(range(5), -1))
print(fence)
answer(26)

9
10
===================================== ANSWER ====================================
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(1, 6)
print(Z**Z)         # equivelant to np.array([x**x for x in Z])
print(2 << Z >> 2)  # equivelant to np.array([((2 << x) >> 2) for x in Z])
print(Z <- Z)       # possibly equivelant to Z < (-Z)
print(1j*Z)         # equivelant to np.array([1j*x for x in Z])
print(Z/1/1)
# print(Z<Z>Z) <-- illegal
print(fence)
answer(27)

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]
===================================== ANSWER ====================================
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
print(fence)
answer(28)

nan
0
[-9.22337204e+18]
===================================== ANSWER ====================================
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


/var/folders/1f/b3qhndss0s3ggtsg9z29mty00000gn/T/ipykernel_34563/4057443260.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/1f/b3qhndss0s3ggtsg9z29mty00000gn/T/ipykernel_34563/4057443260.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/1f/b3qhndss0s3ggtsg9z29mty00000gn/T/ipykernel_34563/4057443260.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
x = np.random.uniform(-10, 10, 20)
print(x)
print(np.where(x > 0, np.ceil(x), np.floor(x)))
print(fence)
answer(29)

[ 9.37811015  7.37743258  6.28213567 -1.60429041  3.18923447 -7.37777306
  7.31656751  5.83840233 -3.07831897  0.12822193  7.69463964 -0.97313565
 -5.93754672  1.32415552 -3.21542015 -3.19494386  7.91949126  2.99599172
  2.06796758 -6.38022909]
[10.  8.  7. -2.  4. -8.  8.  6. -4.  1.  8. -1. -6.  2. -4. -4.  8.  3.
  3. -7.]
===================================== ANSWER ====================================
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
x1 = np.arange(1, 11)
x2 = np.arange(5, 16)
print(x1)
print(x2)
print(np.intersect1d(x1, x2))
print(fence)
answer(30)

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10]
===================================== ANSWER ====================================
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
with np.errstate(all="ignore"):
    np.arange(3) / 0
print(fence)
answer(31)

===================================== ANSWER ====================================
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # np.False_
print(fence)
answer(32)

False
===================================== ANSWER ====================================
np.sqrt(-1) == np.emath.sqrt(-1)


/var/folders/1f/b3qhndss0s3ggtsg9z29mty00000gn/T/ipykernel_34563/2453317103.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # np.False_


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
today = np.datetime64("today")
yesterday = today - 1
tomorrow = today + 1
print(today)
print(yesterday)
print(tomorrow)
now = np.datetime64("now")
print(now)
print(now + 1)
print(now + np.timedelta64(1, "D"))
print(fence)
answer(33)

2024-10-27
2024-10-26
2024-10-28
2024-10-26T16:46:32
2024-10-26T16:46:33
2024-10-27T16:46:32
===================================== ANSWER ====================================
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
print(np.arange(np.datetime64("2016-07"), np.datetime64("2016-08"), np.timedelta64(1, 'D')))
print(fence)
answer(34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
===================================== ANSWER ====================================
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
print((A, B))
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print((A, B))
print(fence)
answer(35)

(array([1., 1., 1.]), array([2., 2., 2.]))
(array([-1.5, -1.5, -1.5]), array([3., 3., 3.]))
===================================== ANSWER ====================================
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
Z = np.random.uniform(1, 11, 10)
print(Z)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

print(fence)
answer(36)

[ 3.49791358  2.6178482   1.46130244  1.71361708  7.18521766 10.75707637
  5.69876448  4.70968751  7.25332598  1.37000547]
[ 3.  2.  1.  1.  7. 10.  5.  4.  7.  1.]
[ 3.  2.  1.  1.  7. 10.  5.  4.  7.  1.]
[ 3.  2.  1.  1.  7. 10.  5.  4.  7.  1.]
[ 3  2  1  1  7 10  5  4  7  1]
[ 3.  2.  1.  1.  7. 10.  5.  4.  7.  1.]
===================================== ANSWER ====================================
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
x = np.zeros((5, 5))
x += np.arange(0, 5) # with broadcasting

print(np.tile(np.arange(5), (5, 1))) # without broadcasting
print(x)
print(fence)
answer(37)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
===================================== ANSWER ====================================
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [48]:
from itertools import count
def gen(n=0):
    stream = count()
    if n:
        yield from [next(stream) for _ in range(n)]
    else:
        yield from count()
print([*gen(5)])
g = gen()
print([next(g) for i in range(10)])

print(np.fromiter(gen(5), dtype=float, count=-1))
print(fence)
answer(38)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0. 1. 2. 3. 4.]
===================================== ANSWER ====================================
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)